apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_USER: {{ .Values.secrets.mongoUser }}
  MONGO_PASS: {{ .Values.secrets.mongoPass }}
  SPRING_MAIL_USERNAME: {{ .Values.secrets.springMailUsername  }}
  SPRING_MAIL_PASSWORD: {{ .Values.secrets.springMailPassword }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}


