apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: purely-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - "until nc -z -v -w30 purely-cart-service 27017; do echo 'Waiting for MongoDB...'; sleep 5; done;"
         
        - name: init-mongo-index
          image: mongo:4.4
          command:
            - /bin/sh
            - -c
            - |
              until mongo --host purely-cart-service \
                          --username root \
                          --password example \
                          --authenticationDatabase admin \
                          --eval '
                            db = db.getSiblingDB("purely_cart_service");

                            // Remove duplicates
                            let seen = {};
                            db.carts.find().forEach(function(doc) {
                              if (seen[doc.userId]) {
                                db.carts.deleteOne({_id: doc._id});
                              } else {
                                seen[doc.userId] = true;
                              }
                            });

                            // Then create the index
                            db.carts.createIndex({"userId":1},{unique:true});
                          '; do
                echo "Retrying...";
                sleep 2;
              done

      containers:
        - name: cart-service
          image: mohamedelrefy20/cart-service:latest
          ports:
            - containerPort: 9060
          envFrom:
          - configMapRef:
              name: cart-service-config
          env:
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGO_USER
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGO_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: purely-app
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 9060
      targetPort: 9060
  type: ClusterIP