apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: purely-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: mohamedelrefy20/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://eureka-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: purely-app
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP