apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
  namespace: purely-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      labels:
        app: category-service
        
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - "until nc -z -v -w30 purely-category-service 27017; do echo 'Waiting for MongoDB...'; sleep 5; done;"
           
      
      containers:
        - name: category-service
          image: mohamedelrefy20/category-service:latest
          ports:
            - containerPort: 9000
          envFrom:
          - configMapRef:
              name: category-service-config
          env:
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGO_USER
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGO_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: category-service
  namespace: purely-app
spec:
  selector:
    app: category-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP