apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: purely-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: mohamedelrefy20/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: spring.application.name
              value: "eureka-server"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: purely-app
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
