apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: purely-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - "until nc -z -v -w30 purely-product-service 27017; do echo 'Waiting for MongoDB...'; sleep 5; done;"
               
      containers:
        - name: product-service
          image: mohamedelrefy20/product-service:latest
          ports:
            - containerPort: 9010
          envFrom:
          - configMapRef:
              name: product-service-config
          env:
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGO_USER
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGO_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: purely-app
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010
  type: ClusterIP