apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: purely-order-service-pvc
  namespace: purely-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purely-order-service
  namespace: purely-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purely-order-service
  template:
    metadata:
      labels:
        app: purely-order-service
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: purely_order_service
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: purely-order-service-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: purely-order-service
  namespace: purely-app
spec:
  selector:
    app: purely-order-service
  ports:
    - port: 27017
      targetPort: 27017
