apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: purely-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - "until nc -z -v -w30 purely-auth-service 27017; do echo 'Waiting for MongoDB...'; sleep 5; done;"
               
      
      containers:
        - name: user-service
          image: mohamedelrefy20/user-service:latest
          ports:
            - containerPort: 9050
          envFrom:
          - configMapRef:
              name: auth-service-config
          env:
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGO_USER
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MONGO_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: purely-app
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
  type: ClusterIP
