apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: purely-app
data:
  SPRING_DATA_MONGODB_HOST: purely-auth-service
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: purely_auth_service
  SPRING_SECURITY_LOG_LEVEL: DEBUG
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
