{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - "until nc -z -v -w30 {{ .Values.userService.init.mongoHost }} {{ .Values.userService.init.mongoPort }}; do echo 'Waiting for MongoDB...'; sleep 5; done;"
        - name: wait-for-eureka
          image: busybox
          command:
            - sh
            - -c
            - "until nc -z -v -w30 {{ .Values.userService.init.eurekaHost }} {{ .Values.userService.init.eurekaPort }}; do echo 'Waiting for Eureka...'; sleep 5; done;"
      containers:
        - name: user-service
          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
          ports:
            - containerPort: {{ .Values.userService.containerPort }}
          envFrom:
            - configMapRef:
                 name: auth-service-config  
            - secretRef:
                name: {{ .Values.secretName }} 


      

    



---



apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.containerPort }}
  type: {{ .Values.userService.service.type }}
{{- end }}
