spring:
    application:
        name: category-service
    data:
        mongodb:
            uri: mongodb://root:example@purely_category_service:27017/purely_category_service?authSource=admin
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9000

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        hostname: category-service