- name: Install Ansible, Prometheus, Grafana, and Alertmanager
  hosts: webservers
  become: true
  tasks:



    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes

    - name: Add Prometheus user
      user:
        name: prometheus
        system: yes
        shell: /sbin/nologin
        create_home: no

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
        - /opt/prometheus

    - name: Download and extract Prometheus
      shell: |
        wget https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz -O /tmp/prometheus.tar.gz
        tar -xzf /tmp/prometheus.tar.gz -C /opt/
        mv /opt/prometheus-2.51.2.linux-amd64/* /opt/prometheus/
        rm -rf /opt/prometheus-2.51.2.linux-amd64
      args:
        creates: /opt/prometheus/prometheus

    - name: Move Prometheus binaries to /usr/local/bin
      shell: |
        mv /opt/prometheus/prometheus /usr/local/bin/
        mv /opt/prometheus/promtool /usr/local/bin/
      args:
        creates: /usr/local/bin/prometheus

    - name: Set ownership for Prometheus
      file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
        recurse: yes
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
        - /opt/prometheus

    - name: Create Prometheus config file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Create Prometheus service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --web.listen-address=:9090
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Add Grafana GPG Key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started


    - name: Download and extract Alertmanager
      shell: |
        wget https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz -O /tmp/alertmanager.tar.gz
        tar -xzf /tmp/alertmanager.tar.gz -C /opt/
        mv /opt/alertmanager-0.27.0.linux-amd64 /opt/alertmanager
      args:
        creates: /opt/alertmanager

    - name: Create systemd service for Alertmanager
      copy:
        dest: /etc/systemd/system/alertmanager.service
        content: |
          [Unit]
          Description=Alertmanager
          After=network.target

          [Service]
          User=prometheus
          Group=prometheus
          ExecStart=/opt/alertmanager/alertmanager --config.file=/opt/alertmanager/alertmanager.yml
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Alertmanager service
      systemd:
        name: alertmanager
        enabled: yes
        state: started