spring:
    application:
        name: user-service
    data:
        mongodb:
            uri: mongodb://root:example@purely_auth_service:27017/purely_auth_service?authSource=admin
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9050

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        hostname: user-service        