spring:
    application:
        name: order-service
    data:
        mongodb:
            uri: mongodb://root:example@purely_order_service:27017/purely_order_service?authSource=admin
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9070

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        hostname: order-service